name: apk
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  path: ^1.7.0
  args: ^1.6.0
  dio: ^3.0.10

dev_dependencies:
  pedantic: ^1.9.0

executables:
  apk: main