name: apk_ci
description: A command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  path: ^1.8.0
  args: ^2.1.1
  dio: ^4.0.0
  g_json: ^4.0.0
  crypto: ^3.0.1

dev_dependencies:
  pedantic: ^1.11.0

executables:
  apk: apk
  fly: fly
  qiniu: qiniu